### ISSUE TITLE
WIP Attachments Fixes

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/challenge-api#107]
The challenge api should accept URLs, then stream out requests for those files.

## Tasks
- [ ] Change the attachments object to be `attachments` not `attachmentIds`
- [ ] Change the validation on attachments, and attachment should be an {id: <uuid>, url: }
  - If you post or PUT [{url}, {url}] with no id property It should create those entries with UUIDs
  - If you PUT with an ID, it should update the URL (if it's different)
- [ ] Add endpoint `GET /v5/challenges/:uuid/attachments`
- [ ] Add endpoint `GET /v5/challenges/:uuid/attachments/:uuid` to stream the file down to the user from S3
- [ ] Update the swagger
- [ ] Update the postman

**Comment by rootelement** [comment]
AV Scan Repo, if necessary:
https://github.com/topcoder-platform/challenge-api/issues/7#issuecomment-517367936
